#          B P R
# BA-PA-RA A A A
# BA-PA    A A -
# BA       A - -
# PA-RA    - A A
# PA       - A -
# RA       - - A
# BA-RA    A - A

Parameters:
  AssumedRoleSessionArn:
    Type: String
    Default: "###NONE###"

Conditions:
  SessionNameNotSet: !Equals
  - !Ref AssumedRoleSessionArn
  - "###NONE###"

Outputs:
  RoleArn:
    Value: !GetAtt Role.Arn
  BucketName:
    Value: !Ref Bucket

Resources:
  PlaceholderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Action: sts:AssumeRole
          Principal:
            "AWS": !Ref AWS::AccountId
      Policies:
        - PolicyName: DenyAll
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Deny
              Action: "*"
              Resource: "*"

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Action: sts:AssumeRole
          Principal:
            "AWS": !Ref AWS::AccountId
      PermissionsBoundary: !Ref Policy
      Policies:
        - PolicyName: Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action: s3:PutObject
              Resource:
              - !Sub "arn:aws:s3:::${Bucket}/R-BA-PA-RA"
              - !Sub "arn:aws:s3:::${Bucket}/R-BA-PA"
              - !Sub "arn:aws:s3:::${Bucket}/R-PA-RA"
              - !Sub "arn:aws:s3:::${Bucket}/R-PA"
            - Effect: Allow
              Action: s3:PutObject
              Resource:
              - !Sub "arn:aws:s3:::${Bucket}/S-BA-PA-RA"
              - !Sub "arn:aws:s3:::${Bucket}/S-BA-PA"
              - !Sub "arn:aws:s3:::${Bucket}/S-PA-RA"
              - !Sub "arn:aws:s3:::${Bucket}/S-PA"
            - Effect: Allow
              Action: s3:PutObject
              Resource:
              - !Sub "arn:aws:s3:::${Bucket}/C1-BA-PA-RA"
              - !Sub "arn:aws:s3:::${Bucket}/C1-BA-PA"
              - !Sub "arn:aws:s3:::${Bucket}/C1-PA-RA"
              - !Sub "arn:aws:s3:::${Bucket}/C1-PA"
            - Effect: Allow
              Action: s3:PutObject
              Resource:
              - !Sub "arn:aws:s3:::${Bucket}/C2-BA-PA-RA"
              - !Sub "arn:aws:s3:::${Bucket}/C2-BA-PA"
              - !Sub "arn:aws:s3:::${Bucket}/C2-PA-RA"
              - !Sub "arn:aws:s3:::${Bucket}/C2-PA"

  Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action: s3:PutObject
          Resource:
          - !Sub "arn:aws:s3:::${Bucket}/R-BA-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/R-BA-PA"
          - !Sub "arn:aws:s3:::${Bucket}/R-BA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/R-BA"
        - Effect: Allow
          Action: s3:PutObject
          Resource:
          - !Sub "arn:aws:s3:::${Bucket}/S-BA-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/S-BA-PA"
          - !Sub "arn:aws:s3:::${Bucket}/S-BA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/S-BA"
        - Effect: Allow
          Action: s3:PutObject
          Resource:
          - !Sub "arn:aws:s3:::${Bucket}/C1-BA-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/C1-BA-PA"
          - !Sub "arn:aws:s3:::${Bucket}/C1-BA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/C1-BA"
        - Effect: Allow
          Action: s3:PutObject
          Resource:
          - !Sub "arn:aws:s3:::${Bucket}/C2-BA-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/C2-BA-PA"
          - !Sub "arn:aws:s3:::${Bucket}/C2-BA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/C2-BA"

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: Role
          Effect: Allow
          Action: s3:PutObject
          Principal:
            AWS: !GetAtt Role.Arn
          Resource:
          - !Sub "arn:aws:s3:::${Bucket}/R-BA-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/R-BA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/R-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/R-RA"
        - Sid: Session
          Effect: Allow
          Action: s3:PutObject
          Principal:
            AWS:
            - !If
              - SessionNameNotSet
              - !Sub "arn:aws:iam::${AWS::AccountId}:assumed-role/${PlaceholderRole}/InvalidRoleSession"
              - !Ref AssumedRoleSessionArn
          Resource:
          - !Sub "arn:aws:s3:::${Bucket}/S-BA-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/S-BA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/S-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/S-RA"
        - Sid: ConditionTest1
          Effect: Allow
          Action: s3:PutObject
          Principal:
            AWS: !Sub "${AWS::AccountId}"
          Resource:
          - !Sub "arn:aws:s3:::${Bucket}/C1-BA-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/C1-BA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/C1-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/C1-RA"
          Condition:
            StringEquals:
              "aws:PrincipalArn": !GetAtt Role.Arn
        - Sid: ConditionTest2
          Effect: Allow
          Action: s3:PutObject
          Principal: "*"
          Resource:
          - !Sub "arn:aws:s3:::${Bucket}/C2-BA-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/C2-BA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/C2-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/C2-RA"
          Condition:
            StringEquals:
              "aws:PrincipalArn": !GetAtt Role.Arn

