#          B P R
# BA-PA-RA A A A
# BA-PA    A A -
# BA       A - -
# PA-RA    - A A
# PA       - A -
# RA       - - A
# BA-RA    A - A

Parameters:
  AssumedRoleSessionArn:
    Type: String
    Default: "###NONE###"

Conditions:
  SessionNameNotSet: !Equals
  - !Ref AssumedRoleSessionArn
  - "###NONE###"

Outputs:
  RoleArn:
    Value: !GetAtt Role.Arn
  BucketName:
    Value: !Ref Bucket

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Action: sts:AssumeRole
          Principal:
            "AWS": !Ref AWS::AccountId
      PermissionsBoundary: !Ref Policy
      Policies:
        - PolicyName: Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action: s3:PutObject
              Resource:
              - !Sub "arn:aws:s3:::${Bucket}/BA-PA-RA"
              - !Sub "arn:aws:s3:::${Bucket}/BA-PA"
              - !Sub "arn:aws:s3:::${Bucket}/PA-RA"
              - !Sub "arn:aws:s3:::${Bucket}/PA"
            - Effect: Allow
              Action: s3:PutObject
              Resource:
              - !Sub "arn:aws:s3:::${Bucket}/C-BA-PA-RA"
              - !Sub "arn:aws:s3:::${Bucket}/C-BA-PA"
              - !Sub "arn:aws:s3:::${Bucket}/C-PA-RA"
              - !Sub "arn:aws:s3:::${Bucket}/C-PA"

  Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action: s3:PutObject
          Resource:
          - !Sub "arn:aws:s3:::${Bucket}/BA-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/BA-PA"
          - !Sub "arn:aws:s3:::${Bucket}/BA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/BA"
        - Effect: Allow
          Action: s3:PutObject
          Resource:
          - !Sub "arn:aws:s3:::${Bucket}/C-BA-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/C-BA-PA"
          - !Sub "arn:aws:s3:::${Bucket}/C-BA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/C-BA"

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: BaseTest
          Effect: Allow
          Action: s3:PutObject
          Principal:
            AWS:
            - !If
              - SessionNameNotSet
              - !GetAtt Role.Arn
              - !Ref AssumedRoleSessionArn
          Resource:
          - !Sub "arn:aws:s3:::${Bucket}/BA-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/BA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/RA"
        - Sid: ConditionTest
          Effect: Allow
          Action: s3:PutObject
          Principal:
            AWS: !Sub "${AWS::AccountId}"
          Resource:
          - !Sub "arn:aws:s3:::${Bucket}/C-BA-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/C-BA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/C-PA-RA"
          - !Sub "arn:aws:s3:::${Bucket}/C-RA"
          Condition:
            StringEquals:
              "aws:PrincipalArn":
                - !If
                  - SessionNameNotSet
                  - !GetAtt Role.Arn
                  - !Ref AssumedRoleSessionArn

